version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - CLIENT_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
    command: bun run dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # در آینده می‌توان سرویس‌های دیگر مثل Redis را اضافه کرد
  redis:
    image: redis:alpine
    ports:
      - "6379:6379" 